---
- name: Install desktop software
  become: true
  apt:
    name:
      - powertop
      - iftop
      - htop
      - iotop
      - baobab
      - libreoffice

- name: Ensure firefox destination
  file:
    path: "{{ app_install_dir }}/firefox"
    state: directory

- name: Download and extract firefox
  unarchive:
    src: "{{ firefox_download_url }}"
    dest: "{{ app_install_dir }}"
    creates: "{{ app_install_dir }}/firefox/firefox"
    remote_src: yes

- name: Create firefox .desktop file
  template:
    src: firefox.desktop.j2
    dest: "{{ app_install_dir }}/applications/firefox.desktop"

- name: Remove system apt firefox
  become: true
  apt:
    name: firefox
    state: absent

- name: Remove system snap firefox
  become: true
  snap:
    name: firefox
    state: absent

- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: check_slack
  failed_when: false
  changed_when: false

- name: Install slack
  become: true
  apt:
    # unfortunately unable to find a magic 'latest' link, however it is evergreen..
    deb: "https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-amd64.deb"
  when: check_slack.rc == 1

- name: Check if MS teams is installed
  command: dpkg-query -W teams
  register: check_teams
  failed_when: false
  changed_when: false

- name: Install MS teams
  become: true
  apt:
    deb: https://go.microsoft.com/fwlink/p/?LinkID=2112886&clcid=0xc09&culture=en-au&country=AU
  when: check_teams.rc == 1

- name: Check if i3 is installed
  command: dpkg-query -W i3
  register: check_i3
  failed_when: false
  changed_when: false

- name: Install i3 key file
  become: true
  apt:
    deb: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2022.02.17_all.deb
  when: check_i3.rc == 1

- name: Add i3 repository
  become: true
  apt_repository:
    repo: "deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"

- name: Install i3
  become: true
  apt:
    name: i3
