---
- name: Install pre-requisites
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl
      - zip

- name: Update apt if older than a day
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400
