---
- name: Install development software
  become: true
  apt:
    name:
      - vim
      - git
      - zsh
      - fonts-powerline
      - yadm
      - python3-pip
      - python3-venv

- name: Install pipx
  pip:
    name: pipx

- name: Generate SSH key pair
  openssh_keypair:
    path: "{{ home }}/.ssh/id_ed25519"
    type: ed25519
  register: ssh_id

- name: Prompt to register SSH key
  pause:
    prompt: "A new SSH key was created, register it where desired:\n\t{{ ssh_id.public_key }}\nAny key to continue"
  when: ssh_id.changed

- name: Check if VS code is installed
  command: dpkg-query -W code
  register: check_code
  failed_when: false
  changed_when: false

- name: Install VS code
  become: true
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  when: check_code.rc == 1

- name: Add docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  become: true
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Create docker group
  become: true
  group:
    name: docker

- name: Add our user to the docker group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
